services:
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_DATABASE: khushbdm_123
        ports:
            - 3306:3306
        volumes:
            - './docker/mysql/data:/var/lib/mysql'

    kitchen:
        build:
            context: ./docker/8.3
            dockerfile: Dockerfile
        volumes:
            - './:/var/www/html'
        depends_on:
            - mysql

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - './docker/nginx/conf.d/:/etc/nginx/conf.d/'
        depends_on:
            - kitchen
            - mysql
